In [1]:
import numpy as np
from numpy import random

Checking the numpy version

In [2]:
print(np.__version__)

1.20.1


creating an array

In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


Numpy Dimenssional Applications

In [4]:
#0-D
print("0-D")
arr = np.array(42)
print(arr)

print()
print("1-D")

#1-D
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

print()
print("2-D")

#2-D
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

print()
print("3-D")

#3-D
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr3)

0-D
42

1-D
[1 2 3 4 5 6]

2-D
[[1 2 3 4]
 [5 6 7 8]]

3-D
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


Check Number of Dimensions

In [5]:
arr = np.array(42)
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


Array Indexing

In [6]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(arr1[0])
print(arr1[1])
print(arr1[2])
print(arr1[3])
print(arr1[4])
print(arr1[5])

print()

print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])
print(arr2[0,3])
print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])
print(arr2[1,3])

print()

print(arr3[0,0,0])
print(arr3[0,0,1])
print(arr3[0,0,2])
print(arr3[0,0,3])
print(arr3[0,0,4])
print(arr3[0,1,0])
print(arr3[0,1,1])
print(arr3[0,1,2])
print(arr3[0,1,3])
print(arr3[0,1,4])
print(arr3[1,0,0])
print(arr3[1,0,1])
print(arr3[1,0,2])
print(arr3[1,0,3])
print(arr3[1,0,4])
print(arr3[1,1,0])
print(arr3[1,1,1])
print(arr3[1,1,2])
print(arr3[1,1,3])
print(arr3[1,1,4])


#Negetive Indexing
print()
print("Negitive Indexing")
print(arr2[1,-1])

1
2
3
4
5
6

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

Negitive Indexing
8


Array Slicing

In [7]:
#arr1 = np.array([1,2,3,4,5,6])
print(arr1[1:5])
print(arr1[4:])
print(arr1[:4])
print(arr1[-3:-1])
print(arr1[1:7:2])


[2 3 4 5]
[5 6]
[1 2 3 4]
[4 5]
[2 4 6]


Checking the Data Type of an Array

In [8]:
#arr1 = np.array([1,2,3,4,5,6])
print(arr1.dtype)

int32


Converting Data Type on Existing Arrays

In [9]:
#arr1 = np.array([1,2,3,4,5,6])
newarr = arr1.astype('f')
print(newarr)
print(newarr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


NumPy Array Copy vs View
#copy returns None.
#view returns original array.

In [10]:
x = arr1.copy()
y = arr1.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5 6]


Array Shape

In [11]:
#arr1 = np.array([1,2,3,4,5,6])
print(arr1.shape)

print()
#creating 5-D array using 1-D array
newarr1 = np.array([1,2,3,4,5,6], ndmin=5)
print(newarr1)
print(newarr1.shape)

(6,)

[[[[[1 2 3 4 5 6]]]]]
(1, 1, 1, 1, 6)


Array Reshaping

In [12]:
#Reshaping 1-D array to 2-D array
print(arr1)
print()
newarr2= arr1.reshape(2,3)
print(newarr2)

print()
#Flattening the arrays
print(newarr2.reshape(-1))

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


Iterating arrays

In [13]:
#arr1 = np.array([1,2,3,4,5,6])
for i in np.nditer(arr1):
    print(i)

print()
for j in np.nditer(arr2):
    print(j)

print()
for k in np.nditer(arr3):
    print(k)
    

1
2
3
4
5
6

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


Enumerated Iteration

In [14]:
for idx, x in np.ndenumerate(arr3):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


Joining of array

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

print()

#Join two 2-D arrays along rows (axis=1)
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[7,8,9],[10,11,12]])
f = np.concatenate((d,e), axis = 1)
print(f)
print()
g = np.concatenate((d,e))
print(g)

[1 2 3 4 5 6]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Joining Arrays Using Stack Functions

In [16]:
#a = np.array([1,2,3])
#b = np.array([4,5,6])
h = np.stack((a,b), axis = 1) 
print(h)
print()

#stacking along Rows
i = np.hstack((a,b))
print(i)
print()

#stacking along Columns
j = np.vstack((a,b))
print(j)
print()

#stacking along Height
k = np.dstack((a,b))
print(k)

[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


Splitting NumPy Arrays

In [17]:
a1 = np.array_split(arr1,3)
print(a1)
print()

a2 = np.array_split(arr1,4)
print(a2)

[array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5]), array([6])]


numpy.zeros()
#numpy.zeros(shape, dtype = None, order = 'C')

In [18]:
b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)
  
a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
  
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Random Number

In [19]:
x=random.randint(100, size=(5))
print(x)
print()

x1 = random.randint(100, size=(3, 5))
print(x1)
print()

#Random float numbers
x2 = random.rand(5)
print(x2)
print()

x3 = random.rand(3, 5)
print(x3)
print()

#Generate Random Number From Array
x4 = random.choice([3, 5, 7, 9])
print(x4)
print()


[ 8 93 92 64  1]

[[28 59  7 78 65]
 [10 12  5 23 57]
 [11 56 60 45 37]]

[0.29353305 0.73876897 0.02901232 0.82298326 0.18469244]

[[0.98849321 0.79961794 0.6371834  0.4534657  0.64697894]
 [0.08822326 0.04943819 0.77430253 0.12746203 0.13439801]
 [0.99054604 0.06624699 0.81131701 0.37027365 0.61009967]]

9



In [20]:
import random
print(random.randrange(1,10))

8


asarray() function

In [21]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)
print()

np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


numpy.arange()

In [22]:
print(np.arange(1, 11))
print(np.arange(1, 14, 4))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  5  9 13]


Linspace

In [23]:
print(np.linspace(1.0, 10.0, num=20))
print()
print(np.linspace(1.0, 5.0, num=5, endpoint=False))

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]

[1.  1.8 2.6 3.4 4.2]


In [24]:
x = np.array([1,2,3,4], dtype=np.complex128)
print(x.itemsize)

16


In [25]:
normal_array = np.random.normal(5, 0.5, 10)
print(np.sort(normal_array))
print()
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

[3.96967431 4.52733253 4.67369366 4.77923391 4.88711608 4.93802873
 5.25814531 5.3001675  5.53357414 5.90974682]

3.9696743059502784
5.909746818549085
4.97767129931688
4.912572401499151
0.5216202399726272


Numpy Dot Product

In [26]:
## Linear algebra
### Dot product: product of two arrays
b1 = np.array([1,2])
b2 = np.array([4,5])
### 1*4+2*5
print(np.dot(b1, b2))

14


Matrix Multiplication

In [27]:
c1 = [[1,2],[3,4]] 
c2 = [[5,6],[7,8]] 
### 1*5+2*7 = 19
print(np.matmul(c1, c2))

[[19 22]
 [43 50]]


How to inverse a matrix using NumPy

In [28]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


How to Calculate the determinant of a matrix using NumPy?

In [29]:
n_array = np.array([[50, 29], [30, 44]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


Rank of a Matrix

In [30]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

Get diagonal of a matrix

In [31]:
# make matrix with numpy
z1 = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = z1.diagonal()
   
print(diag)

[[6 4]]


Matrix transpose

In [32]:
# make matrix with numpy
z2 = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = z2.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


Trace of a matrix

In [33]:
# make matrix with numpy
z3 = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = z3.trace()
    
print(tracem)

[[7]]
